### ISSUE TITLE
32-bit TIFF conversion problem

### ISSUE THREAD

**Issue by ZsuzsannaPuspoki** [joe-jordan/pylibtiff3d#1]
Hello,

I want to read 32-bit TIFF files (3D volumes) with pylibtiff3d. Illustration of the problem: I have created a 32-bit image with ImageJ. It has the following values:
- 30.3197 and -30.5624.

I am running the script:

In [1]: import libtiff3d
In [2]: t1 = libtiff3d.TIFF3D.open("Clipboard.tif")
In [3]: arr1 = t1.read_image()
In [4]: print arr1
[[[ -2.53927115e-13  -9.53510664e-07]]]
In [5]: arr1.dtype
Out[5]: dtype('float32')

The above code is working well for 8-bit images. I am wondering what's going wrong. 
Thanks for your help. 
Zsuzsanna

**Comment by joe-jordan** [comment]
When I added the TIFF3D class I was using it for 8-bit integers, apologies that that wasn't enough testing! I will look into this problem.

**Comment by joe-jordan** [comment]
oh,  I've only just noticed that this is my fork of the main repository. My TIFF3D changes were accepted into the main pylibtiff some time ago, and are available (with more bugfixes since) at:

https://github.com/pearu/pylibtiff

I would be grateful if you:
- test the file used above on the head of the main master branch at the project repo.
- attach the TIFF file to this issue, so I can test it locally.

Thanks!

**Comment by joe-jordan** [comment]
I tested your code on the main pylibtiff and it works fine:

```
# imports:

In [1]: import libtiff

In [4]: import numpy

In [5]: arr = numpy.array

# create sample file:

In [11]: t = libtiff.TIFF.open('test.tif', 'w')

In [12]: t.write_image(arr([[[30.3197 , -30.5624]]], dtype=numpy.dtype('float32')))

In [13]: t.close()

# read sample file back in:

In [15]: t = libtiff.TIFF3D.open('test.tif', 'r')

In [17]: t.read_image()
Out[17]: array([[[ 30.31970024, -30.56240082]]], dtype=float32)

In [18]: t.close()
```

I recommend you use the main pylibtiff for this task.
